### ISSUE TITLE
mand2.0还没有模板吗

### ISSUE THREAD

**Issue by hyhyxu** [mand-mobile/mand-mobile-template#1]
如题

**Comment by xxyan0205** [comment]
2.0的模板要等到正式版发布之后，目前还在rc。可以先用[vue-cli3-example](https://github.com/mand-mobile/vue-cli3-example)，将里面的package.json依赖改成rc版本。

**Comment by hyhyxu** [comment]
> 2.0的模板要等到正式版发布之后，目前还在rc。可以先用[vue-cli3-example](https://github.com/mand-mobile/vue-cli3-example)，将里面的package.json依赖改成rc版本。

好的，我用vue-cli2 只是修改package依赖好像有点问题。我再试试vue-cli3
