### ISSUE TITLE
这个模板在百度浏览器上渲染不出页面

### ISSUE THREAD

**Issue by peng1018** [mand-mobile/mand-mobile-template#2]
百度浏览器报错Uncaught SyntaxError: Unexpected token {

**Comment by xxyan0205** [comment]
> Unexpected

请给一下具体报错截图

**Comment by supergaojian** [comment]
在模版中如果选择的自定义主题的话，就是默认从mand-mobile/components引入的，如果想改回来的话，改成从mand-mobile/lib引入即可
